# PostgreSQL DataSource
management.endpoints.web.exposure.include=*
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# Show SQL
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=20

#Accessing of H2 database console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
